version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports: 
    - 5432:5432
    environment:
      POSTGRES_DATABASE: paypoint
      POSTGRES_USER: ebenhays
      POSTGRES_PASSWORD: L!feisgoog123
    networks:
      - nestjs_network
networks:
  nestjs_network: