export enum SYSTEM_MESSAGE{
    FIRST_TIME_LOGIN_CHANGE_PASSWORD = 'CHANGE PASSWORD ON FIRST LOGIN',
    PASSWORD_EXPIRED_CHANGE_PASSWORD = 'PASSWORD HAS EXPIRED, NEED TO CHANGE IT',
    INVALID_CREDENTIALS = 'INVALID LOGIN DETAILS',
    LOGIN_SUCCESSFUL = 'LOGIN SUCCESSFUL',
    CHANGE_PASSWORD_SUCCESSFUL = 'PASSWORD HAS BEEN CHANGED SUCCESSFULLY',
    NO_RECORD_FOUND = 'RECORD NOT FOUND',
    SUCCESSFUL ='OPERATION SUCCESSFUL',
    BAD_REQUEST = 'BAD REQUEST',
    INTERNAL_SERVER_ERROR = 'THERE WAS A PROBLEM PROCESSING REQUEST',
    RECORD_ALREADY_EXIST = 'RECORD ALREADY EXIST',
    UNKNOWN_ERROR = 'UNKNOWN ERROR HAS OCCURED. TRY AGAIN LATER'
}

export enum SYSTEM_CODE{
    FIRST_TIME_LOGIN_CHANGE_PASSWORD = 100,
    PASSWORD_EXPIRED_CHANGE_PASSWORD,
    INVALID_CREDENTIALS,
    LOGIN_SUCCESSFUL,
    CHANGE_PASSWORD_SUCCESSFUL,
    NO_RECORD_FOUND,
    SUCCESSFUL,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR,
    RECORD_ALREADY_EXIST,
    UNKNOWN_ERROR
}